# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TravelManagePlanner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TravelManagePlanner
  pod 'SnapKit'
  pod 'Alamofire'
  pod 'JJFloatingActionButton'
  pod 'Then'
  target 'TravelManagePlannerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TravelManagePlannerUITests' do
    # Pods for testing
  end

end
